services:
  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: stofgard-app
    container_name: stofgard-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - stofgard-network

  nginx:
    image: nginx:alpine
    container_name: stofgard-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - stofgard-network

  redis:
    image: redis:alpine
    container_name: stofgard-redis
    restart: unless-stopped
    networks:
      - stofgard-network

networks:
  stofgard-network:
    driver: bridge
