services:
  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: stofgard-app
    container_name: stofgard-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - stofgard-network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: stofgard-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - stofgard-network

  redis:
    image: redis:alpine
    container_name: stofgard-redis
    restart: unless-stopped
    networks:
      - stofgard-network

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: stofgard-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'stofgard-mysql:/var/lib/mysql'
    networks:
      - stofgard-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  stofgard-network:
    driver: bridge

volumes:
  stofgard-mysql:
    driver: local
