name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run Tests on PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.4' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, bcmath, opcache, PDO
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Get composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-interaction --no-suggest --optimize-autoloader

      - name: Prepare environment
        run: |
          cp .env.example .env || true
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
          php artisan key:generate --ansi
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Run migrations & seed
        run: php artisan migrate --force --seed
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Run Tests
        run: php artisan test --no-coverage
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-results
          path: ./storage/logs/laravel.log
